In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv('FinalData.csv')
df.head(22)

CH1        CH2        CH3        CH4        CH5       CH6       CH7  \
0   -6.356582  -4.183985 -10.746856  -6.267521  -3.797519 -2.302936 -1.252548   
1   -6.945604  -3.306842 -10.491301  -5.355060  -4.204535 -2.451794 -1.078876   
2   -7.374339  -3.210059 -10.944341  -5.595750  -5.207158 -2.915861 -1.167011   
3   -8.022699  -4.214879 -12.047193  -7.136577  -6.670796 -3.609811 -1.532931   
4   -9.317593  -6.341699 -13.596499  -9.721630  -8.280229 -4.351480 -2.061769   
5  -11.347833  -9.045066 -15.138646 -12.573982  -9.571043 -4.902422 -2.538497   
6  -13.727580 -11.357480 -16.027704 -14.608987 -10.085396 -5.042579 -2.739409   
7  -15.657780 -12.296570 -15.635710 -14.858233  -9.544531 -4.646577 -2.540309   
8  -16.065189 -11.165067 -13.529844 -12.794677  -7.907675 -3.700201 -1.956622   
9  -13.888465  -7.641836  -9.538939  -8.422123  -5.318664 -2.273712 -1.096104   
10  -8.588481  -1.863644  -3.815619  -2.247339  -2.053280 -0.499184 -0.085704   
11  -0.701868   5.383435   3.051153   4.742328   1.470267  1.421057  0.960833   
12   8.026706  12.599540   9.969863  11.198011   4.698724  3.209242  1.933492   
13  15.225856  17.975757  15.551407  15.781702   7.075807  4.568995  2.729387   
14  18.898332  20.188929  18.620399  17.699510   8.263268  5.296659  3.285915   
15  18.268234  19.040525  18.739086  17.047463   8.284639  5.369881  3.608497   
16  14.042345  15.510717  16.433205  14.716613   7.481322  4.946508  3.744095   
17   8.078262  11.279956  13.003575  11.953432   6.343219  4.290719  3.731271   
18   2.714044   8.097053  10.056000   9.890903   5.352487  3.681812  3.585728   
19  -0.070165   7.260290   8.960295   9.256028   4.892503  3.345529  3.329523   
20   0.567974   9.223716  10.362699  10.209888   5.165280  3.394858  3.024490   
21   3.933700  13.328832  13.868129  12.271233   6.092496  3.776579  2.749331   

          CH8        CH9       CH10  ...        CH120      CH121      CH122  \
0   -7.746185   0.471738  -6.161901  ...    -0.020039  -2.472429   8.327164   
1   -6.614024   0.476950  -6.373581  ...     1.339626  -1.503563   8.399263   
2   -5.487274  -1.091632  -7.736202  ...     2.109172  -0.861245   7.858149   
3   -5.089931  -3.724341 -10.143687  ...     1.334883  -1.450996   6.402653   
4   -6.095693  -6.715143 -13.108866  ...    -1.394790  -3.764086   3.939228   
5   -8.844329  -9.460058 -15.817164  ...    -5.473533  -7.390439   0.964761   
6  -13.017964 -11.537113 -17.298231  ...    -9.589652 -11.210074  -1.580985   
7  -17.410857 -12.564220 -16.694256  ...   -12.427728 -13.959871  -2.802353   
8  -20.102499 -12.029400 -13.548552  ...   -13.070301 -14.628959  -2.124832   
9  -19.202040  -9.303129  -8.006057  ...   -10.987175 -12.565097   0.758154   
10 -13.846472  -3.961860  -0.838915  ...    -6.072401  -7.641586   5.876706   
11  -4.814419   3.748668   6.728548  ...     1.013180  -0.602847  12.664744   
12   5.631706  12.654003  13.333624  ...     8.645466   6.836127  19.674685   
13  14.566747  20.819525  17.839839  ...    14.736543  12.552038  24.906468   
14  19.454721  26.151698  19.655002  ...    17.738284  15.013199  26.742834   
15  19.031152  27.226232  18.899846  ...    17.346286  13.957641  24.784764   
16  13.790523  23.997702  16.359146  ...    14.361574  10.290956  19.982668   
17   5.920555  18.034664  13.212865  ...    10.048368   5.486418  14.098517   
18  -1.465411  12.038799  10.631726  ...     5.664882   1.050045   9.040040   
19  -5.621351   8.754019   9.387173  ...     2.339594  -1.762937   6.373632   
20  -5.369264   9.729211   9.627102  ...     0.909194  -2.231149   6.893173   
21  -1.542197  14.510664  10.884648  ...     1.537277  -0.495630  10.211183   

        CH123      CH124      CH125      CH126      CH127      CH128  Label  
0   -7.159484  -7.407739  -3.116786  -5.184181  -3.349719  -3.648696    0.0  
1   -6.161061  -6.157439  -1.761651  -3.521291  -1.393808  -2.770334    0.0  
2   -5.850475  -5.879990  -0.573228  -2.107724  -0.457397  -2.487843    0.0  
3   -6.514009  -

In [3]:
# Preprocessing :
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix
from itertools import product
from sklearn.preprocessing import StandardScaler

# Classifiers
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn import svm
from sklearn import tree
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
from sklearn.naive_bayes import GaussianNB
from sklearn.manifold import TSNE
from sklearn.decomposition import PCA

In [4]:
X = df.drop(['Label'], axis = 1).values
Y = df['Label']

X = StandardScaler().fit_transform(X)

X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.30, random_state = 101)

In [5]:
trainedmodel = LogisticRegression().fit(X_Train,Y_Train)
predictions =trainedmodel.predict(X_Test)
print(confusion_matrix(Y_Test,predictions))
print(classification_report(Y_Test,predictions))

[[  1726 278334]
 [  1461 290429]]
             precision    recall  f1-score   support

        0.0       0.54      0.01      0.01    280060
        1.0       0.51      0.99      0.67    291890

avg / total       0.53      0.51      0.35    571950



In [6]:
# trainedforest = RandomForestClassifier().fit(X_Train,Y_Train)
# predictionforest = trainedforest.predict(X_Test)
# print(confusion_matrix(Y_Test,predictionforest))
# print(classification_report(Y_Test,predictionforest))

In [7]:
trainedsvm = svm.LinearSVC().fit(X_Train, Y_Train)
predictionsvm = trainedsvm.predict(X_Test)
print(confusion_matrix(Y_Test,predictionsvm))
print(classification_report(Y_Test,predictionsvm))

[[ 42802 237258]
 [ 35739 256151]]
             precision    recall  f1-score   support

        0.0       0.54      0.15      0.24    280060
        1.0       0.52      0.88      0.65    291890

avg / total       0.53      0.52      0.45    571950



In [8]:
trainedtree = tree.DecisionTreeClassifier().fit(X_Train, Y_Train)
predictionstree = trainedtree.predict(X_Test)
print(confusion_matrix(Y_Test,predictionstree))
print(classification_report(Y_Test,predictionstree))
# predictionstree = trainedtree.predict_proba(X_Test)
# print(predictionstree)

[[223460  56600]
 [ 57227 234663]]
             precision    recall  f1-score   support

        0.0       0.80      0.80      0.80    280060
        1.0       0.81      0.80      0.80    291890

avg / total       0.80      0.80      0.80    571950



In [9]:
trainedlda = LinearDiscriminantAnalysis().fit(X_Train, Y_Train)
predictionlda = trainedlda.predict(X_Test)
print(confusion_matrix(Y_Test,predictionlda))
print(classification_report(Y_Test,predictionlda))

[[  1726 278334]
 [  1461 290429]]
             precision    recall  f1-score   support

        0.0       0.54      0.01      0.01    280060
        1.0       0.51      0.99      0.67    291890

avg / total       0.53      0.51      0.35    571950



In [10]:
trainednb = GaussianNB().fit(X_Train, Y_Train)
predictionnb = trainednb.predict(X_Test)
print(confusion_matrix(Y_Test,predictionnb))
print(classification_report(Y_Test,predictionnb))

[[114035 166025]
 [ 65815 226075]]
             precision    recall  f1-score   support

        0.0       0.63      0.41      0.50    280060
        1.0       0.58      0.77      0.66    291890

avg / total       0.60      0.59      0.58    571950



In [11]:
pca = PCA(n_components=2,svd_solver='full')
X_pca = pca.fit_transform(X)
# print(pca.explained_variance_)

X_reduced, X_test_reduced, Y_Train, Y_Test = train_test_split(X_pca, Y, test_size = 0.30, random_state = 101)

# pca = PCA(n_components=2,svd_solver='full')
# X_reduced = pca.fit_transform(X_Train)
#X_reduced = TSNE(n_components=2).fit_transform(X_Train, Y_Train)

trainednb = GaussianNB().fit(X_reduced, Y_Train)
trainedtree = tree.DecisionTreeClassifier().fit(X_reduced, Y_Train)
trainedforest = RandomForestClassifier(n_estimators=700).fit(X_reduced,Y_Train)
trainedmodel = LogisticRegression().fit(X_reduced,Y_Train)

# pca = PCA(n_components=2,svd_solver='full')
# X_test_reduced = pca.fit_transform(X_Test)
#X_test_reduced = TSNE(n_components=2).fit_transform(X_Test, Y_Test)

print('Naive Bayes')
predictionnb = trainednb.predict(X_test_reduced)
print(confusion_matrix(Y_Test,predictionnb))
print(classification_report(Y_Test,predictionnb))

print('Decision Tree')
predictionstree = trainedtree.predict(X_test_reduced)
print(confusion_matrix(Y_Test,predictionstree))
print(classification_report(Y_Test,predictionstree))

print('Random Forest')
predictionforest = trainedforest.predict(X_test_reduced)
print(confusion_matrix(Y_Test,predictionforest))
print(classification_report(Y_Test,predictionforest))

print('Logistic Regression')
predictions =trainedmodel.predict(X_test_reduced)
print(confusion_matrix(Y_Test,predictions))
print(classification_report(Y_Test,predictions))

Naive Bayes
[[218079  61981]
 [227892  63998]]
             precision    recall  f1-score   support

        0.0       0.49      0.78      0.60    280060
        1.0       0.51      0.22      0.31    291890

avg / total       0.50      0.49      0.45    571950

Decision Tree
[[141329 138731]
 [139384 152506]]
             precision    recall  f1-score   support

        0.0       0.50      0.50      0.50    280060
        1.0       0.52      0.52      0.52    291890

avg / total       0.51      0.51      0.51    571950

Random Forest
[[141085 138975]
 [132700 159190]]
             precision    recall  f1-score   support

        0.0       0.52      0.50      0.51    280060
        1.0       0.53      0.55      0.54    291890

avg / total       0.52      0.53      0.52    571950

Logistic Regression
[[     9 280051]
 [    60 291830]]
             precision    recall  f1-score   support

        0.0       0.13      0.00      0.00    280060
        1.0       0.51      1.00      0.68    29

In [12]:
# Thanks to: https://scikit-learn.org/stable/auto_examples/ensemble/plot_voting_decision_regions.html
# Plotting decision regions

reduced_data = X_reduced

trainednb = GaussianNB().fit(reduced_data, Y_Train)
trainedtree = tree.DecisionTreeClassifier().fit(X_reduced, Y_Train)
trainedforest = RandomForestClassifier(n_estimators=700).fit(reduced_data,Y_Train)
trainedmodel = LogisticRegression().fit(reduced_data,Y_Train)


x_min, x_max = reduced_data[:, 0].min() - 1, reduced_data[:, 0].max() + 1
y_min, y_max = reduced_data[:, 1].min() - 1, reduced_data[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.1),
                     np.arange(y_min, y_max, 0.1))

f, axarr = plt.subplots(2, 2, sharex='col', sharey='row', figsize=(10, 8))

for idx, clf, tt in zip(product([0, 1], [0, 1]),
                        [trainednb, trainedtree, trainedforest, trainedmodel],
                        ['Naive Bayes Classifier', 'Decision Tree',
                         'Random Forest', 'Logistic Regression']):

    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    

    axarr[idx[0], idx[1]].contourf(xx, yy, Z,cmap=plt.cm.coolwarm, alpha=0.4)
    axarr[idx[0], idx[1]].scatter(reduced_data[:, 0], reduced_data[:, 1], c=Y_Train,
                                  s=20, edgecolor='k')
    axarr[idx[0], idx[1]].set_title(tt)

plt.show()

MemoryError: could not allocate 58720256 bytes